name: Notify daily at 10am PDT
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
jobs:
  uscis-check-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: python notify.py
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
